# Data Cleaner for 2024 Data

In [5]:
import pandas as pd
import re

In [15]:
teams24 = pd.read_csv('./data/2024tourn.csv')

In [16]:
teams24.head()

,RK,TEAM,CONF,G,REC,ADJOE,ADJDE,BARTHAG,EFG%,EFGD%,...,FTR,FTRD,2P%,2P%D,3P%,3P%D,3PR,3PRD,ADJ T.,WAB
0,1,"Houston\n 1 seed, ✅",B12,34,30-4\n15–3,119.1\n16,85.7\n1,.9778\n1,49.7\n228,44.0\n2,...,29.9\n260,39.0\n308,48.4\n260,43.4\n3,34.7\n139,30.0\n13,36.6\n201,40.9\n294,63.4\n349,10.4\n3
1,2,"Connecticut\n 1 seed, ✅",BE,34,31-3\n18–2,126.9\n1,93.8\n14,.9700\n2,57.1\n6,45.1\n3,...,33.3\n162,32.5\n173,58.5\n6,43.7\n6,36.7\n31,31.9\n61,40.9\n87,33.2\n47,64.6\n325,11.0\n1
2,3,"Purdue\n 1 seed, ✅",B10,33,29-4\n17–3,126.2\n2,94.8\n17,.9640\n3,56.0\n13,47.7\n43,...,42.8\n8,23.0\n10,53.2\n69,48.1\n76,40.8\n2,31.4\n41,35.0\n243,37.2\n184,67.6\n168,10.9\n2
3,4,"Iowa St.\n 2 seed, ✅",B12,34,27-7\n13–5,113.5\n51,86.7\n2,.9569\n4,51.9\n106,47.1\n28,...,36.1\n92,35.2\n249,51.7\n117,46.9\n44,34.9\n124,31.5\n48,32.0\n301,45.0\n353,67.6\n170,6.7\n4
4,5,"Auburn\n 4 seed, ✅",SEC,34,27-7\n13–5,120.7\n10,92.2\n5,.9569\n5,54.1\n40,43.4\n1,...,38.2\n48,41.0\n331,54.9\n29,42.8\n1,35.2\n109,29.8\n9,37.5\n177,33.3\n50,69.9\n58,5.4\n9

In [17]:
teams24['SEED'] = teams24.apply(lambda row: row['TEAM'].split('\n')[1], axis=1)
teams24['TEAM'] = teams24.apply(lambda row: row['TEAM'].split('\n')[0], axis=1)

# for col in teams24.columns:
#     try:
#         teams24[col] = teams24.apply(lambda row: row[col].split('\n')[0], axis=1)
#     except AttributeError:
#         pass
# teams24['TEAM'] = teams24.apply(lambda row: row['TEAM'].split('\n')[0], axis=1)
# teams24['W'] = teams24.apply(lambda row: row['REC'].split('-')[0], axis=1)

# for col in teams24.columns:
#     if col != 'TEAM':
#         teams24[col] = pd.to_numeric(teams24[col])

# teams24['WIN_PCT'] = teams24['W']/teams24['G']
# teams24.drop(['G', 'W'], inplace=True, axis=1)
# teams24.rename(columns={"EFG%": "EFG_O", "EFGD%": "EFG_D", "2P%" : "2P_O", "2P%D" : "2P_D", "3P%" : "3P_O", "3P%D" : "3P_D", "ADJ T." : "ADJ_T"}, inplace=True)
# teams24.head()

In [18]:
teams24.head()

,RK,TEAM,CONF,G,REC,ADJOE,ADJDE,BARTHAG,EFG%,EFGD%,...,FTRD,2P%,2P%D,3P%,3P%D,3PR,3PRD,ADJ T.,WAB,SEED
0,1,Houston,B12,34,30-4\n15–3,119.1\n16,85.7\n1,.9778\n1,49.7\n228,44.0\n2,...,39.0\n308,48.4\n260,43.4\n3,34.7\n139,30.0\n13,36.6\n201,40.9\n294,63.4\n349,10.4\n3,"1 seed, ✅"
1,2,Connecticut,BE,34,31-3\n18–2,126.9\n1,93.8\n14,.9700\n2,57.1\n6,45.1\n3,...,32.5\n173,58.5\n6,43.7\n6,36.7\n31,31.9\n61,40.9\n87,33.2\n47,64.6\n325,11.0\n1,"1 seed, ✅"
2,3,Purdue,B10,33,29-4\n17–3,126.2\n2,94.8\n17,.9640\n3,56.0\n13,47.7\n43,...,23.0\n10,53.2\n69,48.1\n76,40.8\n2,31.4\n41,35.0\n243,37.2\n184,67.6\n168,10.9\n2,"1 seed, ✅"
3,4,Iowa St.,B12,34,27-7\n13–5,113.5\n51,86.7\n2,.9569\n4,51.9\n106,47.1\n28,...,35.2\n249,51.7\n117,46.9\n44,34.9\n124,31.5\n48,32.0\n301,45.0\n353,67.6\n170,6.7\n4,"2 seed, ✅"
4,5,Auburn,SEC,34,27-7\n13–5,120.7\n10,92.2\n5,.9569\n5,54.1\n40,43.4\n1,...,41.0\n331,54.9\n29,42.8\n1,35.2\n109,29.8\n9,37.5\n177,33.3\n50,69.9\n58,5.4\n9,"4 seed, ✅"